### ISSUE TITLE
Vue-styleguidist implementation

### ISSUE THREAD

**Issue by rafaesc** [aidewoode/office-ui-fabric-vue#1]
Hello, I see that you are starting to create a great open source, I am sure that [vue-styleguidist](https://github.com/vue-styleguidist/vue-styleguidist) could help you generate a documentation of your props and a playground for your users.

Look at these examples:
http://rafaelescala.com/vue-styleguide/
https://croudsupport.github.io/Croud-Style-Guide/technical/

You could also customize the page to be office-ui.

**Comment by aidewoode** [comment]
Thanks for your advice, the vue-styleguidist is a great tool, I will consider to use it to  refactory my docs later.

**Comment by rafaesc** [comment]
Ok, if you need help you can let me know.

Regards!
