### ISSUE TITLE
Feature Request: ListItem and List Controls

### ISSUE THREAD

**Issue by pabmardo** [aidewoode/office-ui-fabric-vue#11]
Please include when possible the "List" component and "ListItem", I'd like to use it with SharePoint Online and those would make a difference.
Thanks

**Comment by sureshjoshi** [comment]
As you can see, I'm starting some work on this in my fork - apologies for the issue spam, I didn't think that me referencing the issue would make it show up in this repo.

https://github.com/sureshjoshi/office-ui-fabric-vue/tree/feature/11-listitems
